## Colors configuration
[colors-dark]
alpha=1.0
foreground=D3C6AA
background=2D353B

## Normal/regular colors (color palette 0-7)
regular0=343F44  # black
regular1=E67E80  # red
regular2=A7C080  # green
regular3=DBBC7F  # yellow
regular4=7FBBB3  # blue
regular5=D699B6  # magenta
regular6=83C092  # cyan
regular7=D3C6AA  # white

## Bright colors (color palette 8-15)
bright0=475258   # bright black
bright1=E67E80   # bright red
bright2=A7C080   # bright green
bright3=DBBC7F   # bright yellow
bright4=7FBBB3   # bright blue
bright5=D699B6   # bright magenta
bright6=83C092   # bright cyan
bright7=FDF6E3   # bright white
